### ISSUE TITLE
Cannot run captcha_tester.py text

### ISSUE THREAD

**Issue by hanniedo** [aydinnyunus/gpt4-captcha-bypass#5]
I'm running into the issue below:

gpt4-captcha-bypass % python3 captcha_tester.py text
/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/path-to-file/gpt4-captcha-bypass/captcha_tester.py': [Errno 2] No such file or directory

I checked the repo and could not find the captcha_tester.py file. Am I missing anything here?

**Comment by aydinnyunus** [comment]
Hi,

Thank you for your issue. I updated the README.md can you try again ?

**Comment by hanniedo** [comment]
Awesome! I figured it should be main.py. Thank you for your quick response. Things run great on my end currently. Good work!
