### ISSUE TITLE
Issue with puzzle option

### ISSUE THREAD

**Issue by hanniedo** [aydinnyunus/gpt4-captcha-bypass#6]
Hello, result = None in line 152 potentially results in the error below. 

gpt4-captcha-bypass % python3 main.py puzzle
Traceback (most recent call last):
  File "/path-to-file/gpt4-captcha-bypass/main.py", line 295, in <module>
    main()
  File "/path-to-file/gpt4-captcha-bypass/main.py", line 284, in main
    puzzle_test(driver)
  File "/path-to-file/gpt4-captcha-bypass/main.py", line 153, in puzzle_test
    if result < 110:
       ^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by hanniedo** [comment]
I tried to create a PR to fix this but didn't have permission. So small fix for line 152 would be: result = 0

**Comment by aydinnyunus** [comment]
Hi,

Yes you are right but if the response is not integer it is maybe because GPT-4o response is changing over time. But I will update it to 0 it make more sense. Thank you for your support
